version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5002
      - PORT=3001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - MAX_LOGIN_ATTEMPTS=5
      - LOCKOUT_TIME_MINUTES=15
      - FLASK_RUN_PORT=5002
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
